image: python:3.6.8-stretch

before_script:
    - python -m pip install -r requirements.txt
    
test:
    script:
        - cd src
        - python -m unittest discover -v -s ./UnitTest -t . -p *test.py